---

- name: config - templates
  file:
    state=directory
    path={{ nginx_taku_templates_dir }}
    mode=0755

- name: config - sites log dirs
  file:
    state=directory
    path="/var/log/nginx/{{ item }}"
    mode=0755
  with_items:
    - api.takuapp.com
    - admin.takuapp.com
    - stage.api.takuapp.com
    - replywithtaku.me

- name: nginx dynamic configs
  template:
    src={{item}}.j2
    dest={{ nginx_taku_templates_dir }}/{{item}}
  with_items:
    - admin.takuapp.com.tmpl
    - api.takuapp.com.tmpl
    - stage.api.takuapp.com.tmpl

- name: config - replywithtaku.me folder
  file:
    state=directory
    path=/srv/replywithtaku.me
    mode=0755

- name: config - replywithtaku.me html
  template:
    src=redirect-iOS.html.j2
    dest=/srv/replywithtaku.me/redirect-iOS.html

- name: nginx static configs
  template:
    src=replywithtaku.me.j2
    dest={{ nginx_taku_sites_enabled_dir }}/replywithtaku.me


