---

- include_vars: auth.yml

- name: config - templates
  file:
    state=directory
    path={{ nginx_taku_templates_dir }}
    mode=0755

- name: config - sites log dir
  file:
    state=directory
    path="/var/log/nginx/{{ item }}"
    mode=0755
  with_items: "{{ nginx_taku_sites }} "

- name: config - sites srv dir
  file:
    state=directory
    path=/srv/{{ item }}
    mode=0755
  with_items: "{{ nginx_taku_sites }} "

- name: config - replywithtaku.me html
  template:
    src=redirect-iOS.html.j2
    dest=/srv/replywithtaku.me/redirect-iOS.html

- name: config - nginx dynamic configs
  template:
    src={{item}}.j2
    dest={{ nginx_taku_templates_dir }}/{{item}}
  with_items:
    - admin.takuapp.com.tmpl
    - api.takuapp.com.tmpl
    - stage.api.takuapp.com.tmpl
  notify: restart consul-template

- name: config - nginx static configs
  template:
    src=replywithtaku.me.j2
    dest={{ nginx_taku_sites_enabled_dir }}/replywithtaku.me

- name: setup htpasswd
  htpasswd:
    state=present
    path=/etc/nginx/curate_htpasswd
    name={{ nginx_taku_admin_user }}
    password={{ nginx_taku_admin_password }}
    owner=root
    group=nginx
    mode=0640
